version: '3'
services:
  frontend_portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

  backend_jupyter:
    image: gturtu21/bdp2_midterm 
    ports:
      - "80:8888"
    volumes:
      - /home/ubuntu/review/bdp2_recap_exercises/work/:/home/jovyan/work
    environment:
      - GEN_CERT='yes'      
    networks:
      - backend

networks:
    backend:
    frontend:
